server:
  port: 8100

spring:
  application:
    name: gateway-service
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
        max-wait: 1000ms
  cache:
    type: REDIS
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo
          uri: lb://demo-service
          predicates:
          - Path=/api/hhh/**
          filters:
          - StripPrefix=2
          - name: RequestRateLimiter
            args:
              key-resolver: '#{@remoteAddKeyResolver}'
              redis-rate-limiter.replenishRate: 1
              redis-rate-limiter.burstCapacity: 1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
    registryFetchIntervalSeconds: 5
  instance:
    prefer-ip-address: true
