server:
  port: 8000

spring:
  application:
    name: eureka-service

eureka:
  dashboard:
    path: /eureka-serve
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #是否注册到eurekaServer，因为我们是本来就是eurekaServer，所以为false,
    fetchRegistry: false #表示是否从Eureka Server获取注册信息，默认为true。 #因为这是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false。
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  server:
    enableSelfPreservation: false #关闭保护机制
    evictionIntervalTimerInMs: 5000 #剔除失效服务间隔
